### ISSUE TITLE
[Bug] minimal form with file upload fails on email.php

### ISSUE THREAD

**Issue by jadwigo** [jadwigo/bf-prototype#5]
The form:
```yml
# Uploader Form
upload:
    submission:
        ajax: false
    notification:
        enabled: true
        debug: false
        subject: Your message was submitted
        attach_files: true
        from_name: BFP Upload
        from_email: email
        replyto_name: BFP Upload
        replyto_email: email
        to_name: BFP Upload
        to_email: lodewijk@twokings.nl # please change this for your own testing, or I will hunt you down
        debug_address: lodewijk@twokings.nl # please change this for your own testing, or I will hunt you down
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    uploads:
        subdirectory: test
    fields:
        email:
            type: email
            options:
                required: true
                label: Email address
                attr:
                    placeholder: Your email...
                constraints: [ NotBlank, Email ]
        message:
            type: textarea
            options:
                required: true
                label: Your message
                attr:
                    placeholder: Your message...
                    class: myclass
        image:
            type: file
            options:
                required: false
                label: Upload your image
        submit:
            type: submit
            options:
                label: Submit my message
                attr:
                    class: button primary
```

Almost works - you can view the form, submit the form, and a File is uploaded.. but then you get the following error

```
Whoops, looks like something went wrong.

1/1
FatalThrowableError in Email.php line 218:
Call to a member function attach() on null
in Email.php line 218
at Email->getBodyData(object(FormConfig), object(EmailConfig), object(FormData)) in Email.php line 177
at Email->compose(object(FormConfig), object(EmailConfig), object(FormData), object(MetaData)) in Email.php line 136
at Email->handle(object(FormConfig), object(FormData), object(MetaData)) in Email.php line 48
at Email->process(object(LifecycleEvent), 'boltforms.submission_process_email', object(TraceableEventDispatcher)) in Processor.php line 138
at Processor->onProcessLifecycleEvent(object(LifecycleEvent), 'boltforms.submission_process_email', object(TraceableEventDispatcher))
at call_user_func(array(object(Processor), 'onProcessLifecycleEvent'), object(LifecycleEvent), 'boltforms.submission_process_email', 
```
