### ISSUE TITLE
[bug] multiple image upload only attaches last image to email

### ISSUE THREAD

**Issue by jadwigo** [jadwigo/bf-prototype#7]
@GawainLynch
When you upload multiple images the email notification will only have the last image attached

The relevant config:

```yaml
        images:
            type: file
            options:
                multiple: true
                required: false
                label: Upload your other images
                attr:
                    accept: 'image/gif,image/jpeg,image/png'
```
the missing images are uploaded correctly, but are not sent in the email.

This happens in boltforms dev-master f74d4539
